### ISSUE TITLE
Create better error message due to sha1 

### ISSUE THREAD

**Issue by kushaldas** [kushaldas/johnnycanencrypt#48]
We need better error message than this below:

```>>> ks.import_cert("7vpfvq2b.txt")
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: No binding signature at time 2020-11-02T05:12:20Z

Caused by:
    0: Policy rejected non-revocation signature (PositiveCertification)
    1: SHA1 is not considered secure since 2013-01-01T00:00:00Z', src/lib.rs:305:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kdas/code/johnnycanencrypt/johnnycanencrypt/__init__.py", line 182, in import_cert
    uids, fingerprint, keytype, expirationtime, creationtime = parse_cert_file(
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: No binding signature at time 2020-11-02T05:12:20Z

Caused by:
    0: Policy rejected non-revocation signature (PositiveCertification)
    1: SHA1 is not considered secure since 2013-01-01T00:00:00Z

```

**Comment by kushaldas** [comment]
Question is which error should we use in the message of the exception? The main `Err` value, or 0, or 1 ?

**Comment by kushaldas** [comment]
I will go with the main source aka 1.

```python
Traceback (most recent call last):
  File "parsecerts.py", line 8, in <module>
    ks.import_cert("tests/files/test_journalist_key.pub")
  File "/home/kdas/code/rust/johnnycanencrypt/johnnycanencrypt/__init__.py", line 182, in import_cert
    uids, fingerprint, keytype, expirationtime, creationtime = parse_cert_file(
johnnycanencrypt.CryptoError: SHA1 is not considered secure since 2013-01-01T00:00:00Z
```

**Comment by nwalfield** [comment]
The context is not part of the API.  You should concatenate them.  For instance:

```
Johnnycanencrypt.CryptoError: No binding signature at time 2020-11-02T05:12:20Z: Policy rejected non-revocation signature (PositiveCertification): SHA1 is not considered secure since 2013-01-01T00:00:00Z
```
